# Generated by Django 3.2.4 on 2021-08-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_rename_name_language_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='level',
            field=models.CharField(default='one', max_length=30),
            preserve_default=False,
        ),
    ]
