# Generated by Django 3.2.4 on 2021-08-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_language_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='usn',
            field=models.CharField(default='hugosantos', max_length=30),
            preserve_default=False,
        ),
    ]
