# Generated by Django 3.2.4 on 2021-08-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_language_usn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
