# Generated by Django 3.2.4 on 2021-09-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0006_alter_language_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='link',
        ),
    ]
