# Generated by Django 3.2.4 on 2021-06-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20210621_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lista',
            field=models.JSONField(default='hi'),
            preserve_default=False,
        ),
    ]
