# Generated by Django 3.2.3 on 2021-05-19 20:44

import Docente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', Docente.models.LanguagesField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', Docente.models.LanguagesField(max_length=100000)),
                ('group_class', models.ManyToManyField(to='Docente.Alumn')),
            ],
        ),
    ]
