# Generated by Django 3.2.4 on 2021-09-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('teacher', models.CharField(max_length=30)),
                ('link_clases', models.CharField(max_length=255)),
                ('lista_alumnos', models.JSONField()),
            ],
        ),
    ]
