# Generated by Django 3.2.4 on 2021-09-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='language',
        ),
    ]
